import './globals.css'
import { Header } from '@components/Header';
import { Providers } from '@/app/Providers';
import { SearchBox } from '@components/SearchBox/SearchBox';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <Providers>
        <Header/>
        <SearchBox/>
        {children}
      </Providers>
      </body>
    </html>
  )
}
